ddim_config_xl = {
  "_class_name": "DDIMScheduler",
  "_diffusers_version": "0.30.0.dev0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "clip_sample": False,
  "clip_sample_range": 1.0,
  "dynamic_thresholding_ratio": 0.995,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "rescale_betas_zero_snr": False,
  "sample_max_value": 1.0,
  "set_alpha_to_one": False,
  "steps_offset": 1,
  "thresholding": False,
  "timestep_spacing": "leading",
  # "trained_betas": None
}

euler_config_xl = {
  "_class_name": "EulerDiscreteScheduler",
  "_diffusers_version": "0.19.0.dev0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "clip_sample": False,
  "interpolation_type": "linear",
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "sample_max_value": 1.0,
  # "sigma_max": None,
  # "sigma_min": None,
  "set_alpha_to_one": False,
  "skip_prk_steps": True,
  "steps_offset": 1,
  "timestep_spacing": "leading",
  # "trained_betas": None,
}